# Generated by Django 5.0.6 on 2024-07-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_nombre', models.CharField(max_length=50)),
                ('gas_descripcion', models.CharField(max_length=100)),
                ('gas_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas_fecha', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='servicio',
            name='ser_descripcion',
            field=models.CharField(default='descripcion', max_length=100),
        ),
        migrations.AddField(
            model_name='servicio',
            name='ser_duracion',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='servicio',
            name='ser_nombre',
            field=models.CharField(default='valor', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='us_contrasenia',
            field=models.CharField(default='contra', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='us_nombre',
            field=models.CharField(default='user', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='us_rol',
            field=models.CharField(default='rol', max_length=20),
            preserve_default=False,
        ),
    ]
