# Generated by Django 5.0.6 on 2024-07-28 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0004_insumo_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='ins_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.stock'),
        ),
    ]
